version: '3'

services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - ${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    container_name: api_db

    volumes:

      - "./mysql_data:/var/lib/mysql"

  phpmyadmin:

    image: phpmyadmin:5
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_HOST=db

    ports:
      - "8080:80"
